name: Integration with main repository

on:
  push:
    branches:
      - master
      - infra/integration
  pull_request:
    branches:
      - master

jobs:
  integration:
    env:
      GITHUB_TOKEN: ${{ secrets.MAIN_REPO_TOKEN }}
      MAIN_REPO: lucasrattz/cefetdb2.git
    runs-on: ubuntu-latest
    steps:
      - name: Checkout frontend repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Clone main repository
        run: |
          git clone -b development https://pipeline:$GITHUB_TOKEN@github.com/$MAIN_REPO
          cd cefetdb2

      - name: Update frontend
        env:
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          git pull
          rm -rf frontend
          mkdir frontend
          mv ../$REPO_NAME/src frontend/src
          mv ../$REPO_NAME/public frontend/public
          mv ../$REPO_NAME/*.json frontend/

      - name: Commit and push changes to main repository
        run: |
          git config -l | grep 'http\..*\.extraheader' | cut -d= -f1 | \
              xargs -L1 git config --unset-all

          git config --global user.email "pipeline@cefetdb.rattz.xyz"
          git config --global user.name "Pipeline"

          GIT_HASH=$(git rev-parse --short "$GITHUB_SHA")
          git add .
          git commit -m "Frontend update from commit $GIT_HASH in $GITHUB_REF_NAME at $GITHUB_REPOSITORY"
          git push --set-upstream https://pipeline:$GITHUB_TOKEN@github.com/$MAIN_REPO development